# Sourcing all our modules!
source = ~/.config/hypr/modules/moniters.conf
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/envVars.conf
source = ~/.config/hypr/modules/permissions.conf
source = ~/.config/hypr/modules/lookAndFeel.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/windowsAndWorkspaces.conf

# Minecraft window rules

# XWayland fixes
xwayland {
    force_zero_scaling = true
}

# Input behavior
input {
    follow_mouse = 1
    float_switch_override_focus = 0
}

misc {
    focus_on_activate = true
}
